### ISSUE TITLE
Search bar resets when changing window size

### ISSUE THREAD

**Issue by UpcraftLP** [ZenDarva/AlmostEnoughItems#1]
When changing the size of the Minecraft Window (ex. maximizing it or going into fullscreen mode), the search bar is cleared.

MC: 1.13
Rift: 1.0.3-45:dev
AEI: 0.0.5:dev

didn't test in a regular environment, but should be the same.

**Comment by ZenDarva** [comment]
Fixed in Dev.  306df414d8786c36054921ea77eea5795fe77678
