### ISSUE TITLE
[Suggestion] delete items when dropping over the AEI page

### ISSUE THREAD

**Issue by UpcraftLP** [ZenDarva/AlmostEnoughItems#3]
when dropping the mouse itemstack outside the inventory part of the screen, they are dropped into the world.
I'd suggest to delete them instead, if they are released over the AEI page.

**Comment by UpcraftLP** [comment]
quick addition to that: also make it NOT cheat in items when there's an item on the mouse cursor already

**Comment by ZenDarva** [comment]
Implemented in 8f3215e2c13fe446d6188270e34dbbf1a7a4b721
