### ISSUE TITLE
[Bug] AEI overlaps with inventory when potion effect is applied

### ISSUE THREAD

**Issue by UpcraftLP** [ZenDarva/AlmostEnoughItems#4]
when applying a potion effect to a player, the AEI list does not react to the inventory being shifted right.
![ScreenShot](https://user-images.githubusercontent.com/10714589/44180104-ecce2080-a0fa-11e8-8a8f-0d541ed8f290.png)

MC: 1.13
Rift: 1.0.3-45:dev
AEI: 0.0.5:dev

**Comment by ZenDarva** [comment]
Fixed by 085480af3ee009123da5429cc1384148a3d1c037
